<a href="https://colab.research.google.com/github/kalabYibeltal/ML-Onboarding-Tasks/blob/main/Checkpoints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [5]:
import itertools

In [2]:
input = ['A', 'B', 'C']
output = list(itertools.combinations(input,2))
print(*output)

('A', 'B') ('A', 'C') ('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [6]:
input = ['Python', 'is', 'fun']
output = itertools.cycle(input)
output = list(itertools.islice(output,10))
print(*output)

Python is fun Python is fun Python is fun Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [15]:
import glob
print(glob.glob("*.py"))

[]


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [10]:
from bs4 import BeautifulSoup

In [11]:
html_content = '''<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>'''

In [14]:
soup = BeautifulSoup(html_content, 'html.parser')
output = ""
paragraphs = soup.find_all('p')
for ps in paragraphs:
  output += ps.get_text()
print(output)

AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [17]:
import re
input = "AI is good"
output = re.sub(r'AI','Artificial Intelligence', input)
print(output)

Artificial Intelligence is good


**CP6**: Create a numpy array of 10 zeros.

In [19]:
import numpy as np

output = np.zeros(10)
print(output)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**CP7** Create a numpy array of the integers from 10 to 49.

In [20]:
import numpy as np

output = np.arange(10, 49 + 1)
print(output)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [24]:
import numpy as np

output = np.arange(9).reshape(3,3)
print(output)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

In [26]:
print( "Machine learning models require large amounts of data to improve their generalization it means to predict on citcumstances they have not been trained on. And also to capture data variability, learn robust feature representations, and reduce overfitting.")
print("                         ")
print("A large data means a data set that is suffiecent for a machine learning model to learn a specific task.")

Machine learning models require large amounts of data to improve their generalization it means to predict on citcumstances they have not been trained on. And also to capture data variability, learn robust feature representations, and reduce overfitting.
                         
A large data means a data set that is suffiecent for a machine learning model to learn a specific task.


**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

In [29]:
print("1: Adversarial Attacks on Machine Learning Models: Adversarial attacks aim to manipulate machine learning models by giving carefully crafted inputs to deceive or mislead the model's predictions. Also known as injection")

print("        ")

print("2: AI-Powered Misinformation and Manipulation: AI can be exploited to generate and spread misinformation, deepfakes, or manipulated content, leading to the dissemination of false information or malicious activities. This can be acheived by creating massive victim tailored spams..")

print("   ")

print("We can mitigate these problems by using the following techniques; Robust model training, adversarial inputa detection, fact checking, ai text detection ..")

1: Adversarial Attacks on Machine Learning Models: Adversarial attacks aim to manipulate machine learning models by giving carefully crafted inputs to deceive or mislead the model's predictions. Also known as injection
        
2: AI-Powered Misinformation and Manipulation: AI can be exploited to generate and spread misinformation, deepfakes, or manipulated content, leading to the dissemination of false information or malicious activities. This can be acheived by creating massive victim tailored spams..
   
We can mitigate these problems by using the following techniques; Robust model training, adversarial inputa detection, fact checking, ai text detection ..
